#!/bin/bash

# WhatsApp Webhook Configuration Script for REPLAI

echo "=========================================="
echo "WhatsApp Webhook Setup for REPLAI"
echo "=========================================="
echo ""

# Your ngrok URL
NGROK_URL="https://cheer-pledge-lend.ngrok-free.dev"
WEBHOOK_URL="${NGROK_URL}/webhook/whatsapp"
VERIFY_TOKEN="replai_secure_token_2026"

echo "✅ Your REPLAI server is running on: http://localhost:3000"
echo "✅ Ngrok tunnel is active: $NGROK_URL"
echo ""
echo "📋 WhatsApp Webhook Configuration:"
echo "=========================================="
echo ""
echo "Callback URL:"
echo "  $WEBHOOK_URL"
echo ""
echo "Verify Token:"
echo "  $VERIFY_TOKEN"
echo ""
echo "=========================================="
echo ""
echo "🔧 Setup Instructions:"
echo ""
echo "1. Go to: https://developers.facebook.com/apps"
echo "2. Select your WhatsApp app"
echo "3. Click: WhatsApp → Configuration"
echo "4. Find: Webhook section → Click Edit"
echo "5. Enter:"
echo "   - Callback URL: $WEBHOOK_URL"
echo "   - Verify Token: $VERIFY_TOKEN"
echo "6. Click: Verify and Save"
echo "7. Subscribe to: messages"
echo ""
echo "=========================================="
echo ""
echo "📱 Mobile Access:"
echo ""
echo "Open this URL on your mobile:"
echo "  $NGROK_URL"
echo ""
echo "=========================================="
echo ""
echo "✅ Test WhatsApp:"
echo "Send a message to: +1 555-633-0656"
echo ""
echo "Press Ctrl+C to stop ngrok"
echo ""
