#!/bin/bash
# Quick WhatsApp Webhook Setup Script

echo "🔧 WhatsApp Webhook Configuration Helper"
echo "========================================"
echo ""
echo "📋 Your Configuration Details:"
echo ""
echo "Webhook URL: https://cheer-pledge-lend.ngrok-free.dev/webhook/whatsapp"
echo "Verify Token: replai_secure_token_2026"
echo ""
echo "🌐 Open this URL in your browser:"
echo "https://developers.facebook.com/apps/951759947647280/whatsapp-business/wa-settings/"
echo ""
echo "📝 Follow these steps:"
echo ""
echo "1. Scroll down to 'Webhook' section"
echo "2. Click 'Edit' or 'Configure'"
echo "3. Enter Callback URL: https://cheer-pledge-lend.ngrok-free.dev/webhook/whatsapp"
echo "4. Enter Verify Token: replai_secure_token_2026"
echo "5. Click 'Verify and Save'"
echo "6. Subscribe to 'messages' field"
echo "7. Click 'Save'"
echo ""
echo "✅ After setup, test by sending WhatsApp to: +1 555-633-0656"
echo ""
